name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      cache: 'npm'
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm ci
        npm i -g rimraf

    - name: Build production assets
      run: npm run build

    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      with:
        dir: dist
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}